/*
 * Copyright 2003, Heikki Suhonen
 * Distributed under the terms of the MIT License.
 *
 * Authors:
 * 		Heikki Suhonen <heikki.suhonen@gmail.com>
 *
 */


/*
	The word "CANVAS" is a little bit misleading. It will be replaced by
	word such as "IMAGE". In CREATE_CANVAS CANVAS might be better than IMAGE, and
	also in SELECT_CANVAS_SIZE.

*/
#ifndef DUTCH_STRINGS_H
#define	DUTCH_STRINGS_H

#define	DUTCH_ABOUT_ARTPAINT_STRING			"Over ArtPaint"
#define	DUTCH_ABOUT_HELP_STRING				"Toont een venster met informatie over het programma."
#define	DUTCH_ACTIVE_LAYER_STRING				"Actieve laag"
#define	DUTCH_ADD_AREA_STRING					"Zone toevoegen"
#define	DUTCH_ADD_LAYER_HELP_STRING			"Voegt een laag toe boven deze afbeelding."
#define	DUTCH_ADD_LAYER_STRING				"Laag toevoegen"
#define	DUTCH_ADD_LAYER_BEHIND_STRING			"Laag toevoegen op de achtergrond"
#define DUTCH_ADD_LAYER_IN_FRONT_STRING		"Laag toevoegen op de voorgrond"
#define	DUTCH_ADD_ONS_STRING					"Add-ons"
#define	DUTCH_ADJUSTABLE_STRING				"Instelbaar"
#define	DUTCH_ADJUSTABLE_WIDTH_STRING			"Breedte instelbaar"
#define	DUTCH_AIRBRUSH_STRING					"Airbrush"
#define	DUTCH_ALL_LAYERS_COPY_HELP_STRING		"Kopiëert de afbeelding naar het klembord."
#define	DUTCH_ALL_LAYERS_CUT_HELP_STRING		"Kopiëert de afbeelding naar het klembord en verwijderd alle lagen."
#define	DUTCH_ALL_LAYERS_STRING				"Alle lagen"
#define	DUTCH_ALPHA_STRING					"Alpha"
#define	DUTCH_APPLY_CHANGES_STRING			"Aanpassingen toepassen"
#define	DUTCH_BACKGROUND_STRING				"Achtergrond"
#define	DUTCH_BLUE_STRING						"Blauw"
#define	DUTCH_BOTTOM_STRING					"Onder"
#define	DUTCH_BRUSH_STRING					"Penseel"
#define	DUTCH_BRUSH_WINDOW_STRING				"Penseel venster"
#define	DUTCH_BRUSHES_STRING					"Penselen"
#define	DUTCH_CANCEL_STRING					"Annuleren"
#define DUTCH_CANNOT_CREATE_IMAGE_STRING		"Niet voldoende geheugen vrij om de afbeelding te maken. Probeer opnieuw met een kleinere beeldgrootte."
#define	DUTCH_CANVAS_STRING					"Canvas"
#define	DUTCH_CENTER_TO_CORNER_STRING			"Centreer naar hoek"
#define	DUTCH_CHANGES_TAKE_EFFECT_STRING		"Aanpassingen gaan in na het herstarten van het programma."
#define	DUTCH_CHANGE_TRANSPARENCY_HELP_STRING	"Start transparantie aanpassingen van de actieve laag."
#define	DUTCH_CHANGE_TRANSPARENCY_STRING		"Transparantie aanpassen…"
#define	DUTCH_CLEAR_CANVAS_HELP_STRING		"Alle lagen verwijderen."
#define	DUTCH_CLEAR_CANVAS_STRING				"Canvas verwijderen"
#define	DUTCH_CLEAR_LAYER_HELP_STRING			"Verwijderd de aktive laag."
#define	DUTCH_CLEAR_LAYER_STRING				"Verwijder laag"
#define	DUTCH_CLEAR_SELECTION_HELP_STRING		"Verwijderd de selectie zodat alles geselecteerd is."
#define	DUTCH_CLEAR_SELECTION_STRING			"Verwijder selectie"
#define	DUTCH_CLICK_TO_SELECT_COLOR_STRING	"Klik om een penseelkleur te selecteren."
#define	DUTCH_CLOSE_HELP_STRING				"Sluit het huidige venster."
#define	DUTCH_CLOSE_STRING					"Sluiten"
#define	DUTCH_COLOR_AMOUNT_STRING				"Aantal kleuren"
#define	DUTCH_COLOR_MODEL_STRING				"Kleur mode"
#define	DUTCH_COLOR_SET_STRING				"Kleur instellen"
#define	DUTCH_COLOR_STRING					"Kleur"
#define	DUTCH_COLOR_VARIANCE_STRING			"Kleurvariatie"
#define	DUTCH_COLOR_WINDOW_STRING				"Kleur venster"
#define	DUTCH_COLORS_STRING					"Kleuren"
#define	DUTCH_CONFIRM_QUIT_STRING				"Bevestig afsluiten"
#define	DUTCH_CONTINUOUS_STRING				"Continu"
#define	DUTCH_CONTROLLER_STRING				"Controlleer"
#define	DUTCH_COPY_STRING						"Kopiëren"
#define	DUTCH_CORNER_TO_CORNER_STRING			"Hoek tot hoek"
#define	DUTCH_CREATE_CANVAS_STRING			"Canvan maken"
#define	DUTCH_CROP_HELP_STRING				"Start bijsnijden van de afbeelding."
#define	DUTCH_CROP_STRING						"Bijsnijden…"
#define	DUTCH_CROSS_HAIR_CURSOR_STRING		"Kruiscursor"
#define	DUTCH_CURSOR_STRING					"Cursor"
#define	DUTCH_CUT_STRING						"Knip"
#define	DUTCH_DELETE_CURRENT_SET_STRING		"Verwijder huidige set"
#define	DUTCH_DELETE_LAYER_STRING				"Verwijder laag"
#define	DUTCH_DELETE_SELECTED_BRUSH_STRING	"Verwijder geselecteerde penseel"
#define	DUTCH_DISCARD_CHANGES_STRING			"Veranderingen ongedaan maken"
#define	DUTCH_DO_NOT_SAVE_STRING				"Niet opslaan"
#define	DUTCH_DUPLICATE_LAYER_STRING			"Laag dupliceren"
#define DUTCH_EDIT_STRING						"Bewerken"
#define	DUTCH_EFFECTS_WINDOW_STRING			"Effecten venster"
#define	DUTCH_ELLIPSE_STRING					"Ovaal"
#define	DUTCH_EMPTY_PAINT_WINDOW_STRING		"Leeg verfvenster"
#define	DUTCH_ENABLE_ANTI_ALIASING_STRING		"Inschakelen anti-aliasing"
#define	DUTCH_ENABLE_GRADIENT_STRING			"Inschakelen verloop"
#define	DUTCH_ENABLE_PREVIEW_STRING			"Inschakelen voorbeeld"
#define	DUTCH_ENABLE_ROTATION_STRING			"Inschakelen rotatie"
#define	DUTCH_FADE_STRING						"Intensiteit"
#define	DUTCH_FILE_STRING						"Bestand"
#define	DUTCH_FILL_ELLIPSE_STRING				"Vul ovaal"
#define	DUTCH_FILL_RECTANGLE_STRING			"Vul rechthoek"
#define	DUTCH_FINISHING_STRING				"Afronden"
#define	DUTCH_FLIP_HORIZONTAL_LAYER_HELP_STRING		"Draait de actieve laag horizontaal."
#define	DUTCH_FLIP_HORIZONTAL_ALL_LAYERS_HELP_STRING	"Draait alle actieve lagen horizontaal."
#define	DUTCH_FLIP_HORIZONTAL_STRING			"Draai horizontaal"
#define	DUTCH_FLIP_VERTICAL_LAYER_HELP_STRING			"Draait de actieve laag verticaal."
#define	DUTCH_FLIP_VERTICAL_ALL_LAYERS_HELP_STRING	"Draait alle actieve lagen verticaal."
#define	DUTCH_FLIP_VERTICAL_STRING			"Draai verticaal"
#define	DUTCH_FLOOD_FILL_STRING				"Overstroming"
#define	DUTCH_FLOW_STRING						"Vloeien"
#define	DUTCH_FONT_STRING						"Font"
#define	DUTCH_FREE_LINE_STRING				"Vrije lijn"
#define	DUTCH_GLOBAL_SETTINGS_STRING			"Globale instellingen"
#define	DUTCH_GREEN_STRING					"Groen"
#define	DUTCH_GRID_OFF_HELP_STRING			"Schakelt het raster uit."
#define DUTCH_GRID_2_BY_2_HELP_STRING			"Instellen raster op 2 bij 2 pixels."
#define DUTCH_GRID_4_BY_4_HELP_STRING			"Instellen raster op 4 bij 4 pixels."
#define DUTCH_GRID_8_BY_8_HELP_STRING			"Instellen raster op 8 bij 8 pixels."
#define	DUTCH_GROW_SELECTION_HELP_STRING		"Groeit de selectie een beetje in elke richting."
#define	DUTCH_GROW_SELECTION_STRING			"Selection laten groeien"
#define	DUTCH_HAIRS_STRING					"Haren"
#define	DUTCH_HEIGHT_STRING					"Hoogte"
#define	DUTCH_HELP_STRING						"Help"
#define	DUTCH_INSERT_TEXT_HELP_STRING			"Voegt tekst toe in de actieve laag. Gelijk aan de tekst werktuig."
#define	DUTCH_INSERT_TEXT_STRING				"Tekst invoegen…"
#define	DUTCH_INTELLIGENT_SCISSORS_STRING		"Intelligente scharen"
#define	DUTCH_INVERT_SELECTION_HELP_STRING	"Keert de selectie om zodat geselecteerd niet-geselecteerd wordt en vice versa."
#define	DUTCH_INVERT_SELECTION_STRING			"Selectie omkeren"
//#define	DUTCH_KEEP_BRUSH_WINDOW_FRONT_STRING	"Houd het venster Penselen op de voorgrond"
//#define	DUTCH_KEEP_COLOR_WINDOW_FRONT_STRING	"Houd het venster Kleur op de voorgrond"
//#define	DUTCH_KEEP_EFFECTS_WINDOW_FRONT_STRING	"Houd het venster Effecten op de voorgrond"
//#define	DUTCH_KEEP_LAYER_WINDOW_FRONT_STRING	"Houd het venster Lagen op de voorgrond"
//#define	DUTCH_KEEP_TOOL_SELECTION_WINDOW_FRONT_STRING	"Houd het venster Werktuigen selectie op de voorgrond"
//#define	DUTCH_KEEP_TOOL_SETUP_WINDOW_FRONT_STRING	"Houd het venster Werktuigen opstelling op de voorgrond"
#define	DUTCH_KEEP_IN_FRONT_STRING			"Op de voorgrond houden"
#define	DUTCH_LANGUAGE_STRING					"Taal"
#define	DUTCH_LAYER_COPY_HELP_STRING			"Kopiëert de actieve laag naar het klembord.."
#define	DUTCH_LAYER_CUT_HELP_STRING			"Kopiëert de actieve laag naar het klembord en verwijderd de laag."
#define	DUTCH_LAYER_STRING					"Laag"
#define	DUTCH_LAYER_WINDOW_STRING				"Laag venster"
#define	DUTCH_LAYERS_STRING					"Lagen"
#define	DUTCH_LEFT_STRING						"Links"
#define	DUTCH_LITTLE_STRING					"Weinig"
#define	DUTCH_LOCK_PROPORTIONS_STRING			"Vergrendel verhoudingen"
#define	DUTCH_MAG_STRING						"Zoom"
#define	DUTCH_MAGIC_WAND_STRING				"Toverstaf"
#define	DUTCH_MERGE_WITH_BACK_LAYER_STRING	"Samenvoegen met achterlaag"
#define	DUTCH_MERGE_WITH_FRONT_LAYER_STRING	"Samenvoegeen met voorlaag"
#define	DUTCH_MISCELLANEOUS_STRING			"Diversen"
#define	DUTCH_MODE_STRING						"Modus"
#define	DUTCH_MUCH_STRING						"Veel"
#define	DUTCH_NEW_COLOR_SET_STRING			"Nieuwe kleurset"
//#define	DUTCH_NEW_PAINT_WINDOW_STRING			"Nieuw project venster…"
#define	DUTCH_NEW_PROJECT_HELP_STRING			"Maakt een nieuw project venster aan."
#define	DUTCH_NEW_PROJECT_STRING				"Nieuw project…"
#define	DUTCH_NO_OPTIONS_STRING				"Geen opties"
#define	DUTCH_NONE_STRING						"Geen"
#define	DUTCH_OFF_STRING						"Uit"
#define	DUTCH_OK_STRING						"OK"
#define	DUTCH_OPAQUE_STRING					"Ondoorzichtig"
#define	DUTCH_OPEN_COLOR_SET_STRING			"Open Kleurset…"
#define	DUTCH_OPEN_IMAGE_HELP_STRING			"Opent een afbeelding van de schijf."
#define	DUTCH_OPEN_IMAGE_STRING				"Open afbeelding…"
#define	DUTCH_OPEN_PROJECT_HELP_STRING		"Opent een project van de schijf."
#define	DUTCH_OPEN_PROJECT_STRING				"Open project…"
#define	DUTCH_OPEN_STRING						"Open"
#define DUTCH_OPTIONS_STRING					"Opties"
#define	DUTCH_PALETTE_WINDOW_NAME_STRING		"Kleuren"
#define	DUTCH_PASTE_AS_NEW_LAYER_HELP_STRING	"Plakt vorig gekopiëerde laag in het klembord als een nieuwe laag."
#define	DUTCH_PASTE_AS_NEW_LAYER_STRING		"Plak als nieuwe laag"
#define	DUTCH_PASTE_AS_NEW_PROJECT_HELP_STRING	"Plak klembord als nieuw project."
#define	DUTCH_PASTE_AS_NEW_PROJECT_STRING		"Plak als nieuw project"
#define	DUTCH_QUIT_HELP_STRING				"Sluit het programa af."
#define	DUTCH_QUIT_STRING						"Afsluiten"
#define	DUTCH_RANDOM_STRING					"Willekeurig"
#define	DUTCH_RECENT_IMAGES_STRING			"Recente afbeeldingen"
#define	DUTCH_RECENT_PROJECTS_STRING			"Recente projecten"
#define	DUTCH_RECTANGLE_STRING				"Rechthoek"
#define	DUTCH_RED_STRING						"Rood"
#define	DUTCH_REDO_HELP_STRING				"Voert de actie opnieuw uit die het laatst ongedaan is gemaakt."
#define	DUTCH_REDO_NOT_AVAILABLE_STRING		"Opnieuw uitvoeren niet mogelijk"
#define	DUTCH_REDO_STRING						"Opnieuw uitvoeren"
#define	DUTCH_RELEASE_DATE_STRING				"Publicatiedatum: %s"
#define	DUTCH_RESIZE_TO_FIT_HELP_STRING		"Aanpassen van het venster naar de juiste grootte voor de afbeelding en het scherm."
#define	DUTCH_RESIZE_TO_FIT_STRING			"Optimale venstergrootte"
#define	DUTCH_RIGHT_STRING					"Rechts"
#define	DUTCH_ROTATE_ALL_LAYERS_HELP_STRING	"Start het draaien van alle lagen."
#define	DUTCH_ROTATE_LAYER_HELP_STRING		"Start het draaien van de actieve laag."
#define	DUTCH_ROTATE_STRING					"Draaien…"
#define	DUTCH_ROTATE_CW_STRING				"Draai +90°"
#define	DUTCH_ROTATE_CCW_STRING				"Draai -90°"
#define	DUTCH_ROTATION_STRING					"Draaiing"
#define	DUTCH_ROTATING_STRING					"Draaien"
#define	DUTCH_SAVE_CHANGES_STRING				"%s: Je hebt %d aanpassingen gedaan sinds de laatste keer het project was opgeslagen. Wil je deze aanpassingen opslaan?"
#define	DUTCH_SAVE_COLOR_SET_AS_STRING		"Kleurset opslaan als…"
#define	DUTCH_SAVE_COLOR_SET_STRING			"Kleurset opslaan"
#define	DUTCH_SAVE_FORMAT_STRING				"Bestandsformaat opslaan"
#define DUTCH_SAVE_IMAGE_AS_HELP_STRING		"Afbeelding opslaan naar de schijf."
#define	DUTCH_SAVE_IMAGE_AS_STRING			"Afbeelding opslaan als…"
#define	DUTCH_SAVE_IMAGE_HELP_STRING			"Afbeelding wordt opgeslagen op de schijf op met de huidige naam."
#define	DUTCH_SAVE_IMAGE_STRING				"Afbeelding opslaan"
#define	DUTCH_SAVE_PROJECT_AS_HELP_STRING		"Project opslaan naar de schijf."
#define	DUTCH_SAVE_PROJECT_AS_STRING			"Project opslaan als…"
#define	DUTCH_SAVE_PROJECT_HELP_STRING			"Project wordt opgeslagen op de schijf met de huidige naam."
#define	DUTCH_SAVE_PROJECT_STRING				"Project opslaan"
#define	DUTCH_SAVE_STRING						"Opslaan"
#define	DUTCH_SCALE_ALL_LAYERS_HELP_STRING	"Start het schalen van de afbeelding."
#define	DUTCH_SCALE_STRING					"Schalen…"
#define	DUTCH_SELECT_CANVAS_SIZE_STRING		"Selecteer de canvas grootte die je wil."
#define	DUTCH_SELECTED_COLORS_VIEW_MESSAGE1_STRING	"Klik hier om het kleurpaneel te openen."
#define	DUTCH_SET_GRID_STRING					"Raster instellen"
#define	DUTCH_SET_ZOOM_LEVEL_STRING			"Zoom level instellen"
#define	DUTCH_SETTINGS_HELP_STRING			"Toont het venster instellingen."
#define	DUTCH_SETTINGS_STRING					"Instellingen…"
#define	DUTCH_SHAPE_STRING					"Vorm"
#define	DUTCH_SHEAR_STRING					"Neiging"
#define	DUTCH_SHORTCUTS_HELP_STRING			"Opent een pagina die de toetsenbord sneltoetsen toont van ArtPaint."
#define	DUTCH_SHORTCUTS_STRING				"Sneltoetsen…"
#define	DUTCH_SHOW_BRUSH_WINDOW_HELP_STRING	"Opent het venster penselen."
#define	DUTCH_SHOW_BRUSH_WINDOW_STRING		"Toon penseelvenster"
#define	DUTCH_SHOW_LAYER_WINDOW_HELP_STRING	"Opent het venster lagen."
#define	DUTCH_SHOW_LAYER_WINDOW_STRING		"Toon lagenvenster"
#define	DUTCH_SHOW_PALETTE_WINDOW_HELP_STRING	"Opent het venster paletten."
#define	DUTCH_SHOW_PALETTE_WINDOW_STRING		"Toon paletvenster"
#define	DUTCH_SHOW_TOOL_SETUP_WINDOW_HELP_STRING	"Opent het instellingsvenster werktuigen."
#define	DUTCH_SHOW_TOOL_SETUP_WINDOW_STRING		"Toon instellingsvenster werktuigen"
#define	DUTCH_SHOW_TOOL_WINDOW_HELP_STRING	"Opent het selectievenster werktuigen."
#define	DUTCH_SHOW_TOOL_WINDOW_STRING			"Toon selectievenster werktuigen"
#define	DUTCH_SHRINK_SELECTION_HELP_STRING	"Krimpt de selectie een beetje vanuit elke richting."
#define	DUTCH_SHRINK_SELECTION_STRING			"Krimp selectie"
#define	DUTCH_SIZE_STRING						"Grootte"
#define	DUTCH_STANDARD_SIZES_STRING			"Standaard groottes"
#define	DUTCH_STORE_BRUSH_STRING				"Penseel opslaan"
#define	DUTCH_SPEED_STRING					"Snelheid"
#define	DUTCH_SPRAY_STRING					"Verstuif"
#define	DUTCH_SUBTRACT_AREA_STRING			"Gebied verwijderen"
#define	DUTCH_TEXT_COLOR_STRING				"Tekstkleur"
#define	DUTCH_TEXT_STRING						"Tekst"
#define	DUTCH_TOLERANCE_STRING				"Tolerantie"
#define	DUTCH_TOOL_CURSOR_STRING				"Werktuig cursor"
#define	DUTCH_TOOL_SELECTION_WINDOW_STRING	"Werktuig selectievenster"
#define	DUTCH_TOOLS_STRING					"Werktuigen"
#define	DUTCH_TOOL_SETUP_STRING				"Werktuigen instellingen"
#define	DUTCH_TOOL_SETUP_WINDOW_STRING		"Werktuig instellingsvenster"
#define	DUTCH_TOP_STRING						"Boven"
#define	DUTCH_TRANSLATE_ALL_LAYERS_HELP_STRING	"Start verplaatsen alle lagen."
#define	DUTCH_TRANSLATE_LAYER_HELP_STRING		"Start verplaatsen actieve laag."
#define	DUTCH_TRANSLATE_STRING				"Vertaal…"
#define	DUTCH_TRANSPARENT_STRING				"Transparant"
#define	DUTCH_TRANSPARENCY_STRING				"Transparantie"
#define	DUTCH_UNDO_HELP_STRING				"Maakt vorig actie ongedaan."
#define	DUTCH_UNDO_NOT_AVAILABLE_STRING		"Ongedaan maken niet beschikbaar"
#define	DUTCH_UNDO_SETTINGS_STRING			"Ongedaan maken"
#define	DUTCH_UNDO_STRING						"Ongedaan maken"
#define	DUTCH_UNLIMITED_STRING				"Onbegrensd"
#define DUTCH_UNSUPPORTED_FILE_TYPE_STRING	"Het bestandstype %s is niet ondersteund. Je kan een vertaler installeren indien mogelijk."
#define	DUTCH_UNTITLED_STRING					"Ongetiteld"
#define	DUTCH_USE_THE_TOOL_STRING				"Gebruik het werktuid door met de muisknop te duwen."
#define	DUTCH_USER_MANUAL_HELP_STRING			"Opent de hoofddocumentatie voor ArtPaint."
#define	DUTCH_USER_MANUAL_STRING				"Gebruikershandleiding…"
#define	DUTCH_USING_THE_TOOL_STRING			"Gebruik het werktuig."
#define	DUTCH_VISIBLE_STRING					"Zichtbaar"
#define	DUTCH_WAND_TOLERANCE_STRING			"Staf tolerantie"
#define	DUTCH_WIDTH_STRING					"Breedte"
#define	DUTCH_WINDOW_FLOATING_STRING			"Vensters"
#define	DUTCH_WINDOW_STRING					"Venster"
#define	DUTCH_ZOOM_IN_HELP_STRING				"Zoomt in op de afbeelding."
#define	DUTCH_ZOOM_IN_STRING					"Zoom in"
#define	DUTCH_ZOOM_OUT_HELP_STRING			"Zoomt uit op de afbeelding."
#define	DUTCH_ZOOM_OUT_STRING					"Zoom uit"
#define	DUTCH_ZOOM_LEVEL_25_HELP_STRING		"Stelt het zoomniveau in op 25%."
#define	DUTCH_ZOOM_LEVEL_50_HELP_STRING		"Stelt het zoomniveau in op 50%."
#define	DUTCH_ZOOM_LEVEL_100_HELP_STRING		"Stelt het zoomniveau in op 100%."
#define	DUTCH_ZOOM_LEVEL_200_HELP_STRING		"Stelt het zoomniveau in op 200%."
#define	DUTCH_ZOOM_LEVEL_400_HELP_STRING		"Stelt het zoomniveau in op 400%."
#define	DUTCH_ZOOM_LEVEL_800_HELP_STRING		"Stelt het zoomniveau in op 800%."


// Here begin the tool name and help-string definitions.
#define	DUTCH_AIR_BRUSH_TOOL_NAME_STRING		"Luchtborstel"
#define	DUTCH_BLUR_TOOL_NAME_STRING			"Vervaag werktuig"
#define	DUTCH_BRUSH_TOOL_NAME_STRING			"Penseel werktuig"
#define	DUTCH_COLOR_SELECTOR_TOOL_NAME_STRING	"Kleurkiezer"
#define	DUTCH_ELLIPSE_TOOL_NAME_STRING		"Ovaal werktuig"
#define	DUTCH_ERASER_TOOL_NAME_STRING			"Gom"
#define	DUTCH_FILL_TOOL_NAME_STRING			"Vullen werktuig"
#define	DUTCH_FREE_LINE_TOOL_NAME_STRING		"Vrije lijn"
#define	DUTCH_HAIRY_BRUSH_TOOL_NAME_STRING	"Kwast"
#define	DUTCH_RECTANGLE_TOOL_NAME_STRING		"Rechthoek werktuig"
#define	DUTCH_SELECTOR_TOOL_NAME_STRING		"Selectie werktuig"
#define	DUTCH_STRAIGHT_LINE_TOOL_NAME_STRING	"Rechte lijn"
#define	DUTCH_TEXT_TOOL_NAME_STRING			"Tekst werktuig"
#define	DUTCH_TRANSPARENCY_TOOL_NAME_STRING	"Transparantie werktuig"

#define	DUTCH_AIR_BRUSH_TOOL_READY_STRING		"Druk de muisknop om te schilderen met luchtborstel."
#define	DUTCH_BLUR_TOOL_READY_STRING			"Druk de muisknop om de afbeelding te vervagen."
#define	DUTCH_BRUSH_TOOL_READY_STRING			"Druk de muisknop om te schilderen met een penseel."
#define	DUTCH_COLOR_SELECTOR_TOOL_READY_STRING	"Druk de muisknop om een kleur te selecteren."
#define	DUTCH_ELLIPSE_TOOL_READY_STRING		"Druk de muisknop om een ovaal te tekenen."
#define	DUTCH_ERASER_TOOL_READY_STRING			"Druk de muisknop om de gom te gebruiken."
#define	DUTCH_FILL_TOOL_READY_STRING			"Druk de muisknop om te vullen."
#define	DUTCH_FREE_LINE_TOOL_READY_STRING		"Druk de muisknop om een lijn te tekenen uit losse hand."
#define	DUTCH_HAIRY_BRUSH_TOOL_READY_STRING	"Druk de muisknop om te schilderen met een kwast."
#define	DUTCH_RECTANGLE_TOOL_READY_STRING		"Druk de muisknop om een rechthoek te tekenen."
#define	DUTCH_SELECTOR_TOOL_READY_STRING		"Druk de muisknop om een selectie te maken."
#define	DUTCH_STRAIGHT_LINE_TOOL_READY_STRING	"Druk de muisknop om een rechte lijn te tekenen."
#define	DUTCH_TEXT_TOOL_READY_STRING			"Druk de muisknop om tekst in te voegen in de afbeelding."
#define	DUTCH_TRANSPARENCY_TOOL_READY_STRING	"Druk de muisknop om de transparantie van de laag aan te passen."

#define	DUTCH_AIR_BRUSH_TOOL_IN_USE_STRING		"Luchtborstel gebruiken."
#define	DUTCH_BLUR_TOOL_IN_USE_STRING			"Vervagen van de afbeelding."
#define	DUTCH_BRUSH_TOOL_IN_USE_STRING			"Schilderen met een penseel."
#define	DUTCH_COLOR_SELECTOR_TOOL_IN_USE_STRING	"Selecteren van een kleur."
#define	DUTCH_ELLIPSE_TOOL_IN_USE_STRING		"Tekenen van een ovaal."
#define	DUTCH_ERASER_TOOL_IN_USE_STRING			"Afbeelding gommen."
#define	DUTCH_FILL_TOOL_IN_USE_STRING			"Vullen toepassen."
#define	DUTCH_FREE_LINE_TOOL_IN_USE_STRING		"Losse hand lijn tekenen."
#define	DUTCH_HAIRY_BRUSH_TOOL_IN_USE_STRING	"Schilderen met een kwast."
#define	DUTCH_RECTANGLE_TOOL_IN_USE_STRING		"Tekenen van een rechthoek."
#define	DUTCH_SELECTOR_TOOL_IN_USE_STRING		"Maken van een selectie."
#define	DUTCH_STRAIGHT_LINE_TOOL_IN_USE_STRING	"Tekenen van een rechte lijn."
#define	DUTCH_TEXT_TOOL_IN_USE_STRING			"Sleep de tekst naar de juiste positie en stel het uiterlijk in."
#define	DUTCH_TRANSPARENCY_TOOL_IN_USE_STRING	"Transparantie van de laag aanpassen."

#define	DUTCH_DO_CHANGE_TRANSPARENCY_HELP_STRING	"Verander de transparantie met de schuifregelaar."
#define	DUTCH_DO_CROP_HELP_STRING		"Gebruik de handvatten of nummervelden om de nieuwe randen in te stellen ."
#define	DUTCH_DO_ROTATE_HELP_STRING	"Gebruik de primaire muisknow om te draaien, andere knoppen om het draaicentrum in te stellen."
#define	DUTCH_DO_TRANSLATE_HELP_STRING	"Sleep de afbeelding naar de juiste positie."
#define	DUTCH_DO_SCALE_HELP_STRING	"Klik op de afbeelding om een nieuwe schaal in te stellen of stel deze in met de numerieke velden."



// These strings are the contents of the About ArtPaint-window
#define	DUTCH_ABOUT_1_TEXT_STRING				"ArtPaint is schilder en afbeeldings programma voor Haiku."\
												" Het kan gebruikt worden voor een breede variatie aan toepassingen,"\
												" gaande van web-graphics tot foto manipulatie. Bekijk de tutorial in"\
												" de handleiding om te starten."

#define	DUTCH_ABOUT_3_TEXT_STRING				"Voor nieuwe versies van het programma zie:"

#define	DUTCH_ABOUT_4_TEXT_STRING				"Opmerkingen en vragen over het programma kunnen gestuurd worden naar:"

#define	DUTCH_ABOUT_5_TEXT_STRING				"Programmering & Ontwerp"
#define	DUTCH_ABOUT_6_TEXT_STRING				"Engelse documentatie"
#define	DUTCH_ABOUT_7_TEXT_STRING				"Duitse vertaling"
#define	DUTCH_ABOUT_8_TEXT_STRING				"Speciale dank"
#define DUTCH_ABOUT_9_TEXT_STRING				"Bedankt voor inspirerende artikels"
#define	DUTCH_ABOUT_10_TEXT_STRING			"Franse vertaling"

#define DUTCH_MEMORY_ALERT_1_STRING			"Niet voldoende vrij geheugen om een laag toe te voegen ."\
												"Je kan geheugen vrijmaken door het uitshakelen van ongedaan maken en sluiten van andere afbeeldingen. Het is ook een goed idee "\
												"om de afbeelding op te slaan nu, onvoldoende geheugen later kan opslaan moeilijk maken of "\
												"onmogelijk. We verontschuldigen ons voor dit ongemak."

#define	DUTCH_MEMORY_ALERT_2_STRING			"Niet voldoende geheugen op het effect te starten welke je wil gebruiken. Ja kan andere afbeeldingen sluiten en opnieuw proberen. "\
												"Inkrimpen van de diepte van ongedaan maken of volledig uitschakelen hiervan helpt bij het vrijkomen van geheugen. "\
												"Als je andere toepassingen open hebt, sluiten van deze geeft meer geheugen vrij. "\
												"Het is een goed idee om je werk op de slaan nu, als het geheugen helemaal op raakt "\
												"kan het opslaan onmogelijk worden, We verontschuldigen ons voor dit ongemak."

#define	DUTCH_MEMORY_ALERT_3_STRING			"Niet voldoende geheugen op het effect af te ronden welke je wil gebruiken. Ja kan andere afbeeldingen sluiten en opnieuw proberen. "\
												"Inkrimpen van de diepte van ongedaan maken of volledig uitschakelen hiervan helpt bij het vrijkomen van geheugen. "\
												"Als je andere toepassingen open hebt, sluiten van deze geeft meer geheugen vrij. "\
												"Het is een goed idee om je werk op de slaan nu, als het geheugen helemaal op raakt "\
												"kan het opslaan onmogelijk worden, We verontschuldigen ons voor dit ongemak."


#endif
