/*
	Filename:	FrenchStrings.h
	Contents:	Definitions of UI strings in french.
	Author:		Jean-Rémi Taponier

	French Localization (in french) = Localisation Française
*/


/*
	The word "CANVAS" is a little bit misleading. It will be replaced by
	word such as "IMAGE". In CREATE_CANVAS CANVAS might be better than IMAGE, and
	also in SELECT_CANVAS_SIZE.
*/
#ifndef FRENCH_STRINGS_H
#define	FRENCH_STRINGS_H

#define	FRENCH_ABOUT_ARTPAINT_STRING			"À propos de ArtPaint"
#define	FRENCH_ABOUT_HELP_STRING				"Montre des informations sur le programme."
#define	FRENCH_ACTIVE_LAYER_STRING				"Calque actif"
#define	FRENCH_ADD_AREA_STRING					"Ajouter la zone"
#define	FRENCH_ADD_LAYER_HELP_STRING			"Ajoute un calque par-dessus les autres."
#define	FRENCH_ADD_LAYER_STRING				"Ajouter un calque"
#define	FRENCH_ADD_LAYER_BEHIND_STRING			"Ajouter un calque derrière"
#define FRENCH_ADD_LAYER_IN_FRONT_STRING		"Ajouter un calque devant"
#define	FRENCH_ADD_ONS_STRING					"Plug-ins"
#define	FRENCH_ADJUSTABLE_STRING				"Ajustable"
#define	FRENCH_ADJUSTABLE_WIDTH_STRING			"Largeur ajustable"
#define	FRENCH_AIRBRUSH_STRING					"Aérographe"
#define	FRENCH_ALL_LAYERS_COPY_HELP_STRING		"Copie tous les calques en mémoire."
#define	FRENCH_ALL_LAYERS_CUT_HELP_STRING		"Copie tous les calques en mémoire et les efface."
#define	FRENCH_ALL_LAYERS_STRING				"Tous les calques"
#define	FRENCH_ALPHA_STRING					"Alpha"
#define	FRENCH_APPLY_CHANGES_STRING			"Appliquer les modifications"
#define	FRENCH_BACKGROUND_STRING				"Fond"
#define	FRENCH_BLUE_STRING						"Bleu"
#define	FRENCH_BOTTOM_STRING					"Bas"
#define	FRENCH_BRUSH_STRING					"Pinceau"
#define	FRENCH_BRUSH_WINDOW_STRING				"Fenêtre des pinceaux"
#define	FRENCH_BRUSHES_STRING					"Pinceaux"
#define	FRENCH_CANCEL_STRING					"Annuler"
#define FRENCH_CANNOT_CREATE_IMAGE_STRING		"Mémoire insuffisante pour créer l'image. Veuillez essayer avec une taille d'image plus petite."
#define	FRENCH_CANVAS_STRING					"Image"
#define	FRENCH_CENTER_TO_CORNER_STRING			"Du centre au coin"
#define	FRENCH_CHANGES_TAKE_EFFECT_STRING		"Les modifications prendront effet au prochain démarrage du programme."
#define	FRENCH_CHANGE_TRANSPARENCY_HELP_STRING	"Change la transparence du calque actif."
#define	FRENCH_CHANGE_TRANSPARENCY_STRING		"Changer la transparence…"
#define	FRENCH_CLEAR_CANVAS_HELP_STRING		"Efface tous les calques."
#define	FRENCH_CLEAR_CANVAS_STRING				"Effacer l'image"
#define	FRENCH_CLEAR_LAYER_HELP_STRING			"Efface le calque actif."
#define	FRENCH_CLEAR_LAYER_STRING				"Effacer le calque"
#define	FRENCH_CLEAR_SELECTION_HELP_STRING		"Efface toutes les sélections."
#define	FRENCH_CLEAR_SELECTION_STRING			"Effacer la sélection"
#define	FRENCH_CLICK_TO_SELECT_COLOR_STRING	"Cliquer pour sélectionner la couleur du pinceau."
#define	FRENCH_CLOSE_HELP_STRING				"Ferme cette fenêtre."
#define	FRENCH_CLOSE_STRING					"Fermer"
#define	FRENCH_COLOR_AMOUNT_STRING				"Quantité de couleur"
#define	FRENCH_COLOR_MODEL_STRING				"Mode"
#define	FRENCH_COLOR_SET_STRING				"Palette de couleurs"
#define	FRENCH_COLOR_STRING					"Couleur"
#define	FRENCH_COLOR_VARIANCE_STRING			"Variation de couleur"
#define	FRENCH_COLOR_WINDOW_STRING				"Fenêtre des couleurs"
#define	FRENCH_COLORS_STRING					"Couleurs"
#define	FRENCH_CONFIRM_QUIT_STRING				"Confirmer la fermeture du programme"
#define	FRENCH_CONTINUOUS_STRING				"Continu"
#define	FRENCH_CONTROLLER_STRING				"Controlleur"
#define	FRENCH_COPY_STRING						"Copier"
#define	FRENCH_CORNER_TO_CORNER_STRING			"D'un coin à un autre"
#define	FRENCH_CREATE_CANVAS_STRING			"Créer l'image"
#define	FRENCH_CROP_HELP_STRING				"Commence le recadrage de l'image."
#define	FRENCH_CROP_STRING						"Recadrage…"
#define	FRENCH_CROSS_HAIR_CURSOR_STRING		"Curseur croix"
#define	FRENCH_CURSOR_STRING					"Curseur"
#define	FRENCH_CUT_STRING						"Couper"
#define	FRENCH_DELETE_CURRENT_SET_STRING		"Effacer la palette courante"
#define	FRENCH_DELETE_LAYER_STRING				"Supprimer ce calque"
#define	FRENCH_DELETE_SELECTED_BRUSH_STRING	"Supprimer le pinceau sélectionné"
#define	FRENCH_DISCARD_CHANGES_STRING			"Annuler"
#define	FRENCH_DO_NOT_SAVE_STRING				"Ne pas sauver"
#define	FRENCH_DUPLICATE_LAYER_STRING			"Dupliquer ce calque"
#define FRENCH_EDIT_STRING						"Édition"
#define	FRENCH_EFFECTS_WINDOW_STRING			"Fenêtres des effets"
#define	FRENCH_ELLIPSE_STRING					"Ellipse"
#define	FRENCH_EMPTY_PAINT_WINDOW_STRING		"Fenêtre de dessin vide"
#define	FRENCH_ENABLE_ANTI_ALIASING_STRING		"Activer l'anti-aliasing"
#define	FRENCH_ENABLE_GRADIENT_STRING			"Activer le dégradé"
#define	FRENCH_ENABLE_PREVIEW_STRING			"Activer la preview"
#define	FRENCH_ENABLE_ROTATION_STRING			"Activer la rotation"
#define	FRENCH_FADE_STRING						"Fondu"
#define	FRENCH_FILE_STRING						"Fichier"
#define	FRENCH_FILL_ELLIPSE_STRING				"Ellipse remplie"
#define	FRENCH_FILL_RECTANGLE_STRING			"Rectangle rempli"
#define	FRENCH_FINISHING_STRING				"En cours…"
#define	FRENCH_FLIP_HORIZONTAL_LAYER_HELP_STRING		"Inverse horizontallement le calque actif."
#define	FRENCH_FLIP_HORIZONTAL_ALL_LAYERS_HELP_STRING	"Inverse horizontallement tous les calques."
#define	FRENCH_FLIP_HORIZONTAL_STRING			"Inversement horizontal"
#define	FRENCH_FLIP_VERTICAL_LAYER_HELP_STRING			"Inverse verticallement le calque actif."
#define	FRENCH_FLIP_VERTICAL_ALL_LAYERS_HELP_STRING	"Inverse verticallement tous les calques."
#define	FRENCH_FLIP_VERTICAL_STRING			"Inversement vertical"
#define	FRENCH_FLOOD_FILL_STRING				"Remplissage d'une forme"
#define	FRENCH_FLOW_STRING						"Débit"
#define	FRENCH_FONT_STRING						"Police"
#define	FRENCH_FREE_LINE_STRING				"Main levée"
#define	FRENCH_GLOBAL_SETTINGS_STRING			"Préférences générales"
#define	FRENCH_GREEN_STRING					"Vert"
#define	FRENCH_GRID_OFF_HELP_STRING			"Enlève la grille"
#define FRENCH_GRID_2_BY_2_HELP_STRING			"Règle la grille à 2 par 2 pixels."
#define FRENCH_GRID_4_BY_4_HELP_STRING			"Règle la grille à 4 par 4 pixels."
#define FRENCH_GRID_8_BY_8_HELP_STRING			"Règle la grille à 8 par 8 pixels."
#define	FRENCH_GROW_SELECTION_HELP_STRING		"Agrandit la sélection dans toutes les directions."
#define	FRENCH_GROW_SELECTION_STRING			"Agrandir la sélection"
#define	FRENCH_HAIRS_STRING					"Poils"
#define	FRENCH_HEIGHT_STRING					"Hauteur"
#define	FRENCH_HELP_STRING					"Aide"
#define	FRENCH_INSERT_TEXT_HELP_STRING			"Insert du texte dans le calque actif. Identique à l'outil texte."
#define	FRENCH_INSERT_TEXT_STRING				"Insérer du texte…"
#define	FRENCH_INTELLIGENT_SCISSORS_STRING		"Lasso magnétique"
#define	FRENCH_INVERT_SELECTION_HELP_STRING	"Inverse la sélection ; donc ce qui était selectionné devient non-sélectionné et vice versa."
#define	FRENCH_INVERT_SELECTION_STRING			"Inverser la sélection"
//#define	FRENCH_KEEP_BRUSH_WINDOW_FRONT_STRING	"Garder la fenêtre des pinceaux en premier plan"
//#define	FRENCH_KEEP_COLOR_WINDOW_FRONT_STRING	"Garder la fenêtre des couleurs en premier plan"
//#define	FRENCH_KEEP_EFFECTS_WINDOW_FRONT_STRING	"Garder les fenêtres des filtres en premier plan"
//#define	FRENCH_KEEP_LAYER_WINDOW_FRONT_STRING	"Garder la fenêtre des calques en premier plan"
//#define	FRENCH_KEEP_TOOL_SELECTION_WINDOW_FRONT_STRING	"Garder la boîte d'outils en premier plan"
//#define	FRENCH_KEEP_TOOL_SETUP_WINDOW_FRONT_STRING	"Garder la fenêtre de configuration des outils en premier plan"
#define	FRENCH_KEEP_IN_FRONT_STRING			"Garder en premier plan"
#define	FRENCH_LANGUAGE_STRING					"Langage"
#define	FRENCH_LAYER_COPY_HELP_STRING			"Copie le calque actif en mémoire."
#define	FRENCH_LAYER_CUT_HELP_STRING			"Copie le calque actif en mémoire et l'efface."
#define	FRENCH_LAYER_STRING					"Calque"
#define	FRENCH_LAYER_WINDOW_STRING				"Fenêtre des calques"
#define	FRENCH_LAYERS_STRING					"Calques"
#define	FRENCH_LEFT_STRING						"Gauche"
#define	FRENCH_LITTLE_STRING					"Peu"
#define	FRENCH_LOCK_PROPORTIONS_STRING			"Garder les proportions"
#define	FRENCH_MAG_STRING						"Zoom"
#define	FRENCH_MAGIC_WAND_STRING				"Baguette magique"
#define	FRENCH_MERGE_WITH_BACK_LAYER_STRING	"Fusionner avec le calque inférieur"
#define	FRENCH_MERGE_WITH_FRONT_LAYER_STRING	"Fusionner avec le calque supérieur"
#define	FRENCH_MISCELLANEOUS_STRING			"Divers"
#define	FRENCH_MODE_STRING						"Mode"
#define	FRENCH_MUCH_STRING						"Beaucoup"
#define	FRENCH_NEW_COLOR_SET_STRING			"Nouvelle palette"
//#define	FRENCH_NEW_PAINT_WINDOW_STRING			"Nouvelle fenêtre de dessin…"
#define	FRENCH_NEW_PROJECT_HELP_STRING			"Crée une nouvelle fenêtre de dessin vide."
#define	FRENCH_NEW_PROJECT_STRING				"Nouveau projet…"
#define	FRENCH_NO_OPTIONS_STRING				"Pas d'options"
#define	FRENCH_NONE_STRING						"Aucune"
#define	FRENCH_OFF_STRING						"Aucune"
#define	FRENCH_OK_STRING						"OK"
#define	FRENCH_OPAQUE_STRING					"Opaque"
#define	FRENCH_OPEN_COLOR_SET_STRING			"Ouvrir une palette…"
#define	FRENCH_OPEN_IMAGE_HELP_STRING			"Ouvre une image du disque."
#define	FRENCH_OPEN_IMAGE_STRING				"Ouvrir une image…"
#define	FRENCH_OPEN_PROJECT_HELP_STRING		"Ouvre un projet du disque."
#define	FRENCH_OPEN_PROJECT_STRING				"Ouvrir un projet…"
#define	FRENCH_OPEN_STRING						"Ouvrir"
#define	FRENCH_OPTIONS_STRING					"Choix"
#define	FRENCH_PALETTE_WINDOW_NAME_STRING		"Couleurs"
#define	FRENCH_PASTE_AS_NEW_LAYER_HELP_STRING	"Colle le calque précédemment copié en mémoire comme un nouveau calque."
#define	FRENCH_PASTE_AS_NEW_LAYER_STRING		"Copier comme nouveau calque"
#define	FRENCH_PASTE_AS_NEW_PROJECT_HELP_STRING	"Colle le calque en mémoire comme un nouveau projet."
#define	FRENCH_PASTE_AS_NEW_PROJECT_STRING		"Copier comme nouveau projet"
#define	FRENCH_QUIT_HELP_STRING				"Quitte the programme."
#define	FRENCH_QUIT_STRING						"Quitter"
#define	FRENCH_RANDOM_STRING					"Au hazard"
#define	FRENCH_RECENT_IMAGES_STRING			"Images récentes"
#define	FRENCH_RECENT_PROJECTS_STRING			"Projets récents"
#define	FRENCH_RECTANGLE_STRING				"Rectangle"
#define	FRENCH_RED_STRING						"Rouge"
#define	FRENCH_REDO_HELP_STRING				"Rétablir l'action qui a été précédemment annulée."
#define	FRENCH_REDO_NOT_AVAILABLE_STRING		"Pas de rétablissement"
#define	FRENCH_REDO_STRING						"Rétablir"
#define	FRENCH_RELEASE_DATE_STRING				"Réalisé le : %s"
#define	FRENCH_RESIZE_TO_FIT_HELP_STRING		"Redimensionner la fenêtre à la taille de l'image."
#define	FRENCH_RESIZE_TO_FIT_STRING			"Redimensionner"
#define	FRENCH_RIGHT_STRING					"Droite"
#define	FRENCH_ROTATE_ALL_LAYERS_HELP_STRING	"Commence la rotation de tous les calques."
#define	FRENCH_ROTATE_LAYER_HELP_STRING		"Commence la rotation du calque actif."
#define	FRENCH_ROTATE_STRING					"Rotation…"
#define	FRENCH_ROTATE_CW_STRING					"Rotation +90°"
#define	FRENCH_ROTATE_CCW_STRING				"Rotation -90°"
#define	FRENCH_ROTATION_STRING					"Rotation"
#define	FRENCH_ROTATING_STRING					"Angle"
#define	FRENCH_SAVE_CHANGES_STRING				"%s: Vous avez effectué %d modifications depuis la dernière sauvegarde de votre projet. Désirez-vous sauver ces modifications ?"
#define	FRENCH_SAVE_COLOR_SET_AS_STRING		"Sauver la palette sous…"
#define	FRENCH_SAVE_COLOR_SET_STRING			"Sauver la palette"
#define	FRENCH_SAVE_FORMAT_STRING				"Save Format"
#define FRENCH_SAVE_IMAGE_AS_HELP_STRING		"Sauve l'image sur le disque."
#define	FRENCH_SAVE_IMAGE_AS_STRING			"Sauver l'image sous…"
#define	FRENCH_SAVE_IMAGE_HELP_STRING			"Sauve l'image sur le disque sous le nom courant."
#define	FRENCH_SAVE_IMAGE_STRING				"Sauver l'image"
#define	FRENCH_SAVE_PROJECT_AS_HELP_STRING		"Sauve le projet sur le disque."
#define	FRENCH_SAVE_PROJECT_AS_STRING			"Sauver le projet sous…"
#define	FRENCH_SAVE_PROJECT_HELP_STRING			"Sauve le projet sur le disque sous le nom courant."
#define	FRENCH_SAVE_PROJECT_STRING				"Sauver le projet"
#define	FRENCH_SAVE_STRING						"Sauver"
#define	FRENCH_SCALE_ALL_LAYERS_HELP_STRING	"Commence le redimmensionnement de l'image."
#define	FRENCH_SCALE_STRING					"Redimensionner…"
#define	FRENCH_SELECT_CANVAS_SIZE_STRING		"Selectionnez la taille de l'image que vous désirez."
#define	FRENCH_SELECTED_COLORS_VIEW_MESSAGE1_STRING	"Cliquez ici pour ouvrir le paneau de couleurs."
#define	FRENCH_SET_GRID_STRING					"Régler la grille"
#define	FRENCH_SET_ZOOM_LEVEL_STRING			"Régler le zoom"
#define	FRENCH_SETTINGS_HELP_STRING			"Montre la fenêtre des préférences."
#define	FRENCH_SETTINGS_STRING					"Préférences…"
#define	FRENCH_SHAPE_STRING					"Forme"
#define	FRENCH_SHEAR_STRING					"Inclinaison"
#define	FRENCH_SHORTCUTS_HELP_STRING			"Ouvre NetPositive avec une page décrivant les raccourcis clavier de ArtPaint."
#define	FRENCH_SHORTCUTS_STRING				"Raccourcis…"
#define	FRENCH_SHOW_BRUSH_WINDOW_HELP_STRING	"Affiche la fenêtre des pinceaux."
#define	FRENCH_SHOW_BRUSH_WINDOW_STRING		"Afficher les pinceaux"
#define	FRENCH_SHOW_LAYER_WINDOW_HELP_STRING	"Affiche la fenêtre des calques."
#define	FRENCH_SHOW_LAYER_WINDOW_STRING		"Afficher les calques"
#define	FRENCH_SHOW_PALETTE_WINDOW_HELP_STRING	"Affiche la fenêtre des palettes."
#define	FRENCH_SHOW_PALETTE_WINDOW_STRING		"Afficher la palette"
#define	FRENCH_SHOW_TOOL_SETUP_WINDOW_HELP_STRING	"Affiche la fenêtre de configuration des outils."
#define	FRENCH_SHOW_TOOL_SETUP_WINDOW_STRING		"Afficher la configuration des outils"
#define	FRENCH_SHOW_TOOL_WINDOW_HELP_STRING	"Affiche la boîte d'outils."
#define	FRENCH_SHOW_TOOL_WINDOW_STRING			"Afficher la boîte d'outils"
#define	FRENCH_SHRINK_SELECTION_HELP_STRING	"Réduit la sélection dans toute les directions."
#define	FRENCH_SHRINK_SELECTION_STRING			"Réduire la sélection"
#define	FRENCH_SIZE_STRING						"Taille"
#define	FRENCH_STANDARD_SIZES_STRING			"Tailles standards"
#define	FRENCH_STORE_BRUSH_STRING				"Sauver"
#define	FRENCH_SPEED_STRING					"Vitesse"
#define	FRENCH_SPRAY_STRING					"Bombe"
#define	FRENCH_SUBTRACT_AREA_STRING			"Ôter la zone"
#define	FRENCH_TEXT_COLOR_STRING				"Couleur du texte"
#define	FRENCH_TEXT_STRING						"Texte"
#define	FRENCH_TOLERANCE_STRING				"Tolérance"
#define	FRENCH_TOOL_CURSOR_STRING				"Curseur outil"
#define	FRENCH_TOOL_SELECTION_WINDOW_STRING	"Boîte d'outils"
#define	FRENCH_TOOLS_STRING					"Outils"
#define	FRENCH_TOOL_SETUP_STRING				"Configuration des outils"
#define	FRENCH_TOOL_SETUP_WINDOW_STRING		"Fenêtre de configuration"
#define	FRENCH_TOP_STRING						"Haut"
#define	FRENCH_TRANSLATE_ALL_LAYERS_HELP_STRING	"Commence à bouger tous les calques."
#define	FRENCH_TRANSLATE_LAYER_HELP_STRING		"Commence à bouger le calque actif."
#define	FRENCH_TRANSLATE_STRING				"Translation…"
#define	FRENCH_TRANSPARENT_STRING				"Transparent"
#define	FRENCH_TRANSPARENCY_STRING				"Transparence"
#define	FRENCH_UNDO_HELP_STRING				"Annuler l'action précédente."
#define	FRENCH_UNDO_NOT_AVAILABLE_STRING		"Pas d'annulation"
#define	FRENCH_UNDO_SETTINGS_STRING			"Annulation"
#define	FRENCH_UNDO_STRING						"Annuler"
#define	FRENCH_UNLIMITED_STRING				"Illimitée"
#define FRENCH_UNSUPPORTED_FILE_TYPE_STRING	"Le type du fichier %s n'est pas supporté. Essayer d'installer un Translator si c'est possible."
#define	FRENCH_UNTITLED_STRING					"Sans titre"
#define	FRENCH_USE_THE_TOOL_STRING				"Utilisez l'outil en cliquant sur le bouton de la souris."
#define	FRENCH_USER_MANUAL_HELP_STRING			"Ouvre la documentation de ArtPaint avec NetPositive."
#define	FRENCH_USER_MANUAL_STRING				"Manuel de l'utilisateur…"
#define	FRENCH_USING_THE_TOOL_STRING			"Outil en utilisation."
#define	FRENCH_VISIBLE_STRING					"Visible"
#define	FRENCH_WAND_TOLERANCE_STRING			"Tolérance de la baguette"
#define	FRENCH_WIDTH_STRING					"Largeur"
#define	FRENCH_WINDOW_FLOATING_STRING			"Fenêtres"
#define	FRENCH_WINDOW_STRING					"Fenêtre"
#define	FRENCH_ZOOM_IN_HELP_STRING				"Zoom dans l'image."
#define	FRENCH_ZOOM_IN_STRING					"Zoom avant"
#define	FRENCH_ZOOM_OUT_HELP_STRING			"Zoom en arrière de l'image."
#define	FRENCH_ZOOM_OUT_STRING					"Zoom arrière"
#define	FRENCH_ZOOM_LEVEL_25_HELP_STRING		"Règle le zoom à 25%."
#define	FRENCH_ZOOM_LEVEL_50_HELP_STRING		"Règle le zoom à 50%."
#define	FRENCH_ZOOM_LEVEL_100_HELP_STRING		"Règle le zoom à 100%."
#define	FRENCH_ZOOM_LEVEL_200_HELP_STRING		"Règle le zoom à 200%."
#define	FRENCH_ZOOM_LEVEL_400_HELP_STRING		"Règle le zoom à 400%."
#define	FRENCH_ZOOM_LEVEL_800_HELP_STRING		"Règle le zoom à 800%."


// Here begin the tool name and help-string definitions.
#define	FRENCH_AIR_BRUSH_TOOL_NAME_STRING		"Aérographe"
#define	FRENCH_BLUR_TOOL_NAME_STRING			"Flou"
#define	FRENCH_BRUSH_TOOL_NAME_STRING			"Pinceau"
#define	FRENCH_COLOR_SELECTOR_TOOL_NAME_STRING	"Pipette"
#define	FRENCH_ELLIPSE_TOOL_NAME_STRING		"Ellipse"
#define	FRENCH_ERASER_TOOL_NAME_STRING			"Gomme"
#define	FRENCH_FILL_TOOL_NAME_STRING			"Remplissage"
#define	FRENCH_FREE_LINE_TOOL_NAME_STRING		"Main levée"
#define	FRENCH_HAIRY_BRUSH_TOOL_NAME_STRING	"Brosse"
#define	FRENCH_RECTANGLE_TOOL_NAME_STRING		"Rectangle"
#define	FRENCH_SELECTOR_TOOL_NAME_STRING		"Sélection"
#define	FRENCH_STRAIGHT_LINE_TOOL_NAME_STRING	"Ligne droite"
#define	FRENCH_TEXT_TOOL_NAME_STRING			"Texte"
#define	FRENCH_TRANSPARENCY_TOOL_NAME_STRING	"Tranparence"

#define	FRENCH_AIR_BRUSH_TOOL_READY_STRING		"Pressez le bouton de la souris pour dessiner avec l'aérographe."
#define	FRENCH_BLUR_TOOL_READY_STRING			"Pressez le bouton de la souris pour atténuer l'image."
#define	FRENCH_BRUSH_TOOL_READY_STRING			"Pressez le bouton de la souris pour peindre avec un pinceau."
#define	FRENCH_COLOR_SELECTOR_TOOL_READY_STRING	"Pressez le bouton de la souris pour sélectionner une couleur."
#define	FRENCH_ELLIPSE_TOOL_READY_STRING		"Pressez le bouton de la souris pour tracer une ellipse."
#define	FRENCH_ERASER_TOOL_READY_STRING			"Pressez le bouton de la souris pour gommer."
#define	FRENCH_FILL_TOOL_READY_STRING			"Pressez le bouton de la souris pour remplir une zone."
#define	FRENCH_FREE_LINE_TOOL_READY_STRING		"Pressez le bouton de la souris pour dessiner à main levée."
#define	FRENCH_HAIRY_BRUSH_TOOL_READY_STRING	"Pressez le bouton de la souris pour dessiner avec une brosse."
#define	FRENCH_RECTANGLE_TOOL_READY_STRING		"Pressez le bouton de la souris pour tracer un rectangle."
#define	FRENCH_SELECTOR_TOOL_READY_STRING		"Pressez le bouton de la souris pour faire une sélection."
#define	FRENCH_STRAIGHT_LINE_TOOL_READY_STRING	"Pressez le bouton de la souris pour tracer une ligne droite."
#define	FRENCH_TEXT_TOOL_READY_STRING			"Pressez le bouton de la souris pour insérer du texte dans l'image."
#define	FRENCH_TRANSPARENCY_TOOL_READY_STRING	"Pressez le bouton de la souris pour ajuster la transparence du calque."

#define	FRENCH_AIR_BRUSH_TOOL_IN_USE_STRING		"Aérographe en utilisation."
#define	FRENCH_BLUR_TOOL_IN_USE_STRING			"Atténuation de l'image."
#define	FRENCH_BRUSH_TOOL_IN_USE_STRING			"Pinceau en utilisation."
#define	FRENCH_COLOR_SELECTOR_TOOL_IN_USE_STRING	"Sélection d'une couleur."
#define	FRENCH_ELLIPSE_TOOL_IN_USE_STRING		"Traçage d'une ellipse."
#define	FRENCH_ERASER_TOOL_IN_USE_STRING			"Effaçage de l'image."
#define	FRENCH_FILL_TOOL_IN_USE_STRING			"Remplissage en cours."
#define	FRENCH_FREE_LINE_TOOL_IN_USE_STRING		"Dessin à main levée."
#define	FRENCH_HAIRY_BRUSH_TOOL_IN_USE_STRING	"Brosse en utilisation."
#define	FRENCH_RECTANGLE_TOOL_IN_USE_STRING		"Traçage d'un rectangle."
#define	FRENCH_SELECTOR_TOOL_IN_USE_STRING		"Sélection en cours."
#define	FRENCH_STRAIGHT_LINE_TOOL_IN_USE_STRING	"Traçage d'une ligne droite."
#define	FRENCH_TEXT_TOOL_IN_USE_STRING			"Mettez le texte dans la bonne position et réglez son apparence."
#define	FRENCH_TRANSPARENCY_TOOL_IN_USE_STRING	"Ajustement de la transparence du calque."

#define	FRENCH_DO_CHANGE_TRANSPARENCY_HELP_STRING	"Changez la transparence avec le slider."
#define	FRENCH_DO_CROP_HELP_STRING		"Utilisez les poignées ou les champs numériques pour ajuster les nouveaux bords."
#define	FRENCH_DO_ROTATE_HELP_STRING	"Utilisez le bouton gauche de la souris pour tourner, et le droit pour modifier le centre de rotation."
#define	FRENCH_DO_TRANSLATE_HELP_STRING	"Bougez l'image dans la position souhaitée."
#define	FRENCH_DO_SCALE_HELP_STRING	"Cliquez sur l'image pour régler la nouvelle taille or réglez-la avec les champs numériques."



// These strings are the contents of the About ArtPaint-window
#define	FRENCH_ABOUT_1_TEXT_STRING				"ArtPaint est un logiciel de dessin et de retouche d'image pour Haiku."\
												" Il peut être utilisé pour réaliser un grand choix de travaux depuis le design d'un site web"\
												" à la retouche de photos. Pour bien débuter, regardez le didacticiel dans le manuel."

#define	FRENCH_ABOUT_3_TEXT_STRING				"Les nouvelles versions de ArtPaint peuvent être trouvées ici :"

#define	FRENCH_ABOUT_4_TEXT_STRING				"Vous pouvez me faire parvenir vos commentaires et questions à :"

#define	FRENCH_ABOUT_5_TEXT_STRING				"Programmation & conception"
#define	FRENCH_ABOUT_6_TEXT_STRING				"Documentation anglaise"
#define	FRENCH_ABOUT_7_TEXT_STRING				"Localisation allemande"
#define	FRENCH_ABOUT_8_TEXT_STRING				"Remerciements à"
#define FRENCH_ABOUT_9_TEXT_STRING				"Merci pour les articles encourageant"
#define	FRENCH_ABOUT_10_TEXT_STRING				"Localisation française"

#define FRENCH_MEMORY_ALERT_1_STRING			"Mémoire insuffisante pour ajouter un nouveau calque."\
												"Vous pouvez libérer de la mémoire en désactivant la fonction d'annulation et en fermant les autres images ouvertes. Vous devriez aussi "\
												"sauver l'image maintenant car vous ne pourez peut-être pas le faire plus tard si vous n'avez plus du tout de "\
												"mémoire. Je suis vraiment désolé pour ce problème."


#define	FRENCH_MEMORY_ALERT_2_STRING			"Mémoire insuffisante pour appliquer cet effet. Vous pouvez fermer des images puis essayer à nouveau. "\
												"Réduire le niveau d'annulation ou désactiver l'annulation peut faire récupérer de la mémoire. "\
												"Si vous avez d'autre applications ouvertes, les fermer vous libérera de la mémoire. "\
												"Vous devriez aussi sauver votre travail maintenant, car si la mémoire est entièrement utilisée, "\
												"il vous sera impossible de sauver. Je suis vraiment désolé pour ce problème."


#define	FRENCH_MEMORY_ALERT_3_STRING			"Mémoire insuffisante pour finir d'appliquer cet effet. Vous pouvez fermer des images puis essayer à nouveau. "\
												"Réduire le niveau d'annulation ou désactiver l'annulation peut faire récupérer de la mémoire. "\
												"Si vous avez d'autre applications ouvertes, les fermer vous libérera de la mémoire. "\
												"Vous devriez aussi sauver votre travail maintenant, car si la mémoire est entièrement utilisée, "\
												"il vous sera impossible de sauver. Je suis vraiment désolé pour ce problème."

#endif
