/*

	Filename:	FinnishStrings.h
	Contents:	Definitions of UI strings in finnish.
	Author:		Heikki Suhonen

*/


#ifndef FINNISH_STRINGS_H
#define	FINNISH_STRINGS_H

#define	FINNISH_ACTIVE_LAYER_STRING				"Aktiivinen Kerros"
#define	FINNISH_ADD_AREA_STRING					"Lisää Alue"
#define	FINNISH_ADD_LAYER_HELP_STRING			"Lisää kerroksen nykyisen kerroksen päälle."
#define	FINNISH_ADD_LAYER_STRING				"Lisää Kerros"
#define	FINNISH_ADD_LAYER_BEHIND_STRING			"Lisää Kerros Taakse"
#define FINNISH_ADD_LAYER_IN_FRONT_STRING		"Lisää Kerros Eteen"
#define	FINNISH_ADD_ONS_STRING					"Add-Onit"
#define	FINNISH_ADJUSTABLE_STRING				"Säädettävät"
#define	FINNISH_ADJUSTABLE_WIDTH_STRING			"Säädettävä Leveys"
#define	FINNISH_AIRBRUSH_STRING					"Maaliruisku"
#define	FINNISH_ALL_LAYERS_COPY_HELP_STRING		"Kopioi kuvan leikepöydälle."
#define	FINNISH_ALL_LAYERS_CUT_HELP_STRING		"Kopioi kuvan leikepöydälle ja tyhjentää sen."
#define	FINNISH_ALL_LAYERS_STRING				"Kaikki Kerrokset"
#define	FINNISH_APPLY_CHANGES_STRING			"Toteuta Muutokset"
#define	FINNISH_BACKGROUND_STRING				"Tausta"
#define	FINNISH_BOTTOM_STRING					"Ala"
#define	FINNISH_BRUSHES_STRING					"Siveltimet"
#define FINNISH_CANNOT_CREATE_IMAGE_STRING		"Liian vähän muistia kuvan luomiseen. Ole hyvä ja yritä uudelleen pienemmällä kuvakoolla"
#define	FINNISH_CANVAS_STRING					"Kuva"
#define	FINNISH_CENTER_TO_CORNER_STRING			"Keskustasta Keskustaan"
#define	FINNISH_CHANGE_TRANSPARENCY_HELP_STRING	"Aloittaa aktiivisen kerroksen läpinäkyvyyden säätämisen."
#define	FINNISH_CHANGE_TRANSPARENCY_STRING		"Muuta Läpinäkyvyyttä…"
#define	FINNISH_CLEAR_CANVAS_HELP_STRING		"Tyhjentää kuvan taustavärillä."
#define	FINNISH_CLEAR_CANVAS_STRING				"Tyhjennä Kuva"
#define	FINNISH_CLEAR_LAYER_HELP_STRING			"Tyhjentää aktiivisen kerroksen."
#define	FINNISH_CLEAR_LAYER_STRING				"Tyhjennä Kerros"
#define	FINNISH_CLEAR_SELECTION_HELP_STRING		"Poistaa valinnan niin, että kaikki tulee valituksi."
#define	FINNISH_CLEAR_SELECTION_STRING			"Poista Valinta"
#define	FINNISH_CLOSE_HELP_STRING				"Sulkee aktiivisen ikkunan."
#define	FINNISH_CLOSE_STRING					"Sulje"
#define	FINNISH_COLOR_AMOUNT_STRING				"Värin Määrä"
#define	FINNISH_COLOR_STRING					"Väri"
#define	FINNISH_COLOR_VARIANCE_STRING			"Värin Satunnaisuus"
#define	FINNISH_COLORS_STRING					"Värit"
#define	FINNISH_CONTINUOUS_STRING				"Jatkuva"
#define	FINNISH_CONTROLLER_STRING				"Kontrolleri"
#define	FINNISH_COPY_STRING						"Kopioi"
#define	FINNISH_CORNER_TO_CORNER_STRING			"Kulmasta Kulmaan"
#define	FINNISH_CREATE_CANVAS_STRING			"Luo Piirtoalusta"
#define	FINNISH_CROP_HELP_STRING				"Aloitaa kuvan rajaamisen."
#define	FINNISH_CROP_STRING						"Rajaa…"
#define	FINNISH_CUT_STRING						"Leikkaa"
#define	FINNISH_DELETE_CURRENT_SET_STRING		"Tuhoa Nykyinen Paletti"
#define	FINNISH_DELETE_LAYER_STRING				"Tuhoa Kerros"
#define	FINNISH_DELETE_SELECTED_BRUSH_STRING	"Tuhoa Valittu Sivellin"
#define	FINNISH_DISCARD_CHANGES_STRING			"Hylkää Muutokset"
#define	FINNISH_DUPLICATE_LAYER_STRING			"Kopioi Kerros"
#define FINNISH_EDIT_STRING						"Muokkaa"
#define	FINNISH_ELLIPSE_STRING					"Ellipsi"
#define	FINNISH_ENABLE_ANTI_ALIASING_STRING		"Pehmennä Reunat"
#define	FINNISH_ENABLE_GRADIENT_STRING			"Tee Gradientti"
#define	FINNISH_ENABLE_PREVIEW_STRING			"Näytä Preview"
#define	FINNISH_ENABLE_ROTATION_STRING			"Tee Kierto"
#define	FINNISH_FADE_STRING						"Häivytä"
#define	FINNISH_FILE_STRING						"Tiedosto"
#define	FINNISH_FILL_ELLIPSE_STRING				"Täytä Ellipsi"
#define	FINNISH_FILL_RECTANGLE_STRING			"Täytä Suorakaide"
#define	FINNISH_FINISHING_STRING				"Viimeistelee"
#define	FINNISH_FLIP_HORIZONTAL_LAYER_HELP_STRING		"Peilaa aktiivisen kerroksen vaakasuunnassa."
#define	FINNISH_FLIP_HORIZONTAL_ALL_LAYERS_HELP_STRING	"Peilaa kuvan vaakasuunnassa."
#define	FINNISH_FLIP_HORIZONTAL_STRING			"Peilaa Vaakasuunnasa"
#define	FINNISH_FLIP_VERTICAL_LAYER_HELP_STRING			"Peilaa aktiivisen kerroksen pystysuunnassa."
#define	FINNISH_FLIP_VERTICAL_ALL_LAYERS_HELP_STRING	"Peilaa kuvan pystysuunnassa."
#define	FINNISH_FLIP_VERTICAL_STRING			"Peilaa Pystysuunnassa"
#define	FINNISH_FLOOD_FILL_STRING				"Tulvatäyttö"
#define	FINNISH_FLOW_STRING						"Virtaus"
#define	FINNISH_FONT_STRING						"Kirjasin"
#define	FINNISH_FREE_LINE_STRING				"Vapaa Viiva"
#define	FINNISH_GLOBAL_SETTINGS_STRING			"Asetukset"
#define	FINNISH_GRID_OFF_HELP_STRING			"Laittaa ruudukon pois päältä."
#define FINNISH_GRID_2_BY_2_HELP_STRING			"Asettaa ruudukon 2*2 pikselin kokoiseksi."
#define FINNISH_GRID_4_BY_4_HELP_STRING			"Asettaa ruudukon 4*4 pikselin kokoiseksi."
#define FINNISH_GRID_8_BY_8_HELP_STRING			"Asettaa ruudukon 8*8 pikselin kokoiseksi."
#define	FINNISH_GROW_SELECTION_HELP_STRING		"Kasvattaa valintaa hieman joka suuntaan."
#define	FINNISH_GROW_SELECTION_STRING			"Kasvata Valintaa"
#define	FINNISH_HAIRS_STRING					"Harjakset"
#define	FINNISH_HEIGHT_STRING					"Korkeus"
#define	FINNISH_HELP_STRING						"Apua"
#define	FINNISH_INSERT_TEXT_HELP_STRING			"Lisää tekstiä aktiiviseen kerrokseen. Sama kuin tekstityökalu"
#define	FINNISH_INSERT_TEXT_STRING				"Lisää Tekstiä…"
#define	FINNISH_INTELLIGENT_SCISSORS_STRING		"Älykkäät Sakset"
#define	FINNISH_INVERT_SELECTION_HELP_STRING	"Invertoi valinnan siten, että valitusta tulee ei-valittua ja päinvastoin."
#define	FINNISH_INVERT_SELECTION_STRING			"Invertoi Valinta"
#define	FINNISH_KEEP_BRUSH_WINDOW_FRONT_STRING	"Pidä Sivellin-ikkuna Edessä"
#define	FINNISH_KEEP_COLOR_WINDOW_FRONT_STRING	"Pidä Väri-ikkuna Edessä"
#define	FINNISH_KEEP_EFFECTS_WINDOW_FRONT_STRING	"Pidä Efekti-ikkuna Edessä"
#define	FINNISH_KEEP_LAYER_WINDOW_FRONT_STRING	"Pidä Kerros-ikkuna Edessä"
#define	FINNISH_KEEP_TOOL_SELECTION_WINDOW_FRONT_STRING	"Pidä Työkalun Valinta -ikkuna Edessä"
#define	FINNISH_KEEP_TOOL_SETUP_WINDOW_FRONT_STRING	"Pidä Työkalun Asetus -ikkuna Edessä"
#define	FINNISH_LANGUAGE_STRING					"Kieli"
#define	FINNISH_LAYER_COPY_HELP_STRING			"Kopioi aktiivisen kerroksen leikepöydälle."
#define	FINNISH_LAYER_CUT_HELP_STRING			"Kopioi aktiivisen kerroksen leikepöydälle ja tyhjentää kerroksen."
#define	FINNISH_LAYER_STRING					"Kerros"
#define	FINNISH_LAYERS_STRING					"Kerrokset"
#define	FINNISH_LEFT_STRING						"Vasen"
#define	FINNISH_LITTLE_STRING					"Vähän"
#define	FINNISH_LOAD_COLOR_SET_STRING			"Avaa Paletti…"
#define	FINNISH_LOCK_PROPORTIONS_STRING			"Lukitse Suhteet"
#define	FINNISH_MAG_STRING						"Suur"
#define	FINNISH_MAGIC_WAND_STRING				"Taikasauva"
#define	FINNISH_MERGE_WITH_BACK_LAYER_STRING	"Yhdistä Alempaan Kerrokseen"
#define	FINNISH_MERGE_WITH_FRONT_LAYER_STRING	"Yhdistä Ylempään Kerrokseen"
#define	FINNISH_MODE_STRING						"Moodi"
#define	FINNISH_MUCH_STRING						"Paljon"
#define	FINNISH_NEW_COLOR_SET_STRING			"Uusi Paletti"
#define	FINNISH_NEW_PAINT_WINDOW_STRING			"Uusi Maalausikkuna…"
#define	FINNISH_NEW_PROJECT_HELP_STRING			"Luo uuden, tyhjän maalausikkunan."
#define	FINNISH_NEW_PROJECT_STRING				"Uusi Projekti…"
#define	FINNISH_NO_OPTIONS_STRING				"Ei Optioita"
#define	FINNISH_NONE_STRING						"Ei Lainkaan"
#define	FINNISH_OFF_STRING						"Pois Päältä"
#define	FINNISH_OK_STRING						"OK"
#define	FINNISH_OPAQUE_STRING					"Läpinäkymätön"
#define	FINNISH_OPEN_IMAGE_HELP_STRING			"Avaa kuvan levyltä."
#define	FINNISH_OPEN_IMAGE_STRING				"Avaa Kuva…"
#define	FINNISH_OPEN_PROJECT_HELP_STRING		"Avaa projektin levyltä."
#define	FINNISH_OPEN_PROJECT_STRING				"Avaa Projekti…"
#define	FINNISH_PALETTE_WINDOW_NAME_STRING		"Värit"
#define	FINNISH_PASTE_AS_NEW_LAYER_HELP_STRING	"Liimaa leikepöydän sisällön uudeksi kerrokseksi."
#define	FINNISH_PASTE_AS_NEW_LAYER_STRING		"Liimaa Uutena Kerroksena"
#define	FINNISH_PASTE_AS_NEW_PROJECT_HELP_STRING	"Luo leikepöydän sisällöstä uuden projektin."
#define	FINNISH_PASTE_AS_NEW_PROJECT_STRING		"Liimaa Uutena Projektina"
#define	FINNISH_QUIT_HELP_STRING				"Lopettaa koko ohjelman."
#define	FINNISH_QUIT_STRING						"Lopeta"
#define	FINNISH_RANDOM_STRING					"Satunnainen"
#define	FINNISH_RECTANGLE_STRING				"Suorakaide"
#define	FINNISH_REDO_HELP_STRING				"Tekee uudellee edellisen perutun tapahtuman."
#define	FINNISH_REDO_NOT_AVAILABLE_STRING		"Ei Voi Tehdä Uudelleen"
#define	FINNISH_REDO_STRING						"Tee Uudelleen"
#define	FINNISH_RESIZE_TO_FIT_HELP_STRING		"Muuttaa ikkunan koon kuvaruutuun ja kuvaan nähden sopivaksi."
#define	FINNISH_RESIZE_TO_FIT_STRING			"Sovita Ikkunan Koko"
#define	FINNISH_RIGHT_STRING					"Oikea"
#define	FINNISH_ROTATE_ALL_LAYERS_HELP_STRING	"Aloittaa kuvan kiertämisen."
#define	FINNISH_ROTATE_LAYER_HELP_STRING		"Aloittaa aktiivisen kerroksen kiertämisen."
#define	FINNISH_ROTATE_STRING					"Kierrä…"
#define	FINNISH_ROTATION_STRING					"Kierto"
#define	FINNISH_ROTATING_STRING					"Kiertää"
#define	FINNISH_SAVE_COLOR_SET_STRING			"Talleta Paletti…"
#define	FINNISH_SAVE_FORMAT_STRING				"Tallennusmuoto"
#define FINNISH_SAVE_IMAGE_AS_HELP_STRING		"Tallentaa kuvan levylle uudella nimellä."
#define	FINNISH_SAVE_IMAGE_AS_STRING			"Talenna Kuva Uudella Nimellä…"
#define	FINNISH_SAVE_IMAGE_HELP_STRING			"Tallentaa kuvan levylle nykyisellä nimellä."
#define	FINNISH_SAVE_IMAGE_STRING				"Tallenna Kuva"
#define	FINNISH_SAVE_PROJECT_AS_HELP_STRING		"Tallentaa projektin levylle uudella nimellä."
#define	FINNISH_SAVE_PROJECT_AS_STRING			"Tallenna Projekti Uudella Nimellä…"
#define	FINNISH_SAVE_PROJECT_HELP_STRING		"Tallenta projektin levylle nykyisellä nimellä."
#define	FINNISH_SAVE_PROJECT_STRING				"Tallenna Projekti"
#define	FINNISH_SCALE_ALL_LAYERS_HELP_STRING	"Aloittaa kuvan skaalauksen."
#define	FINNISH_SCALE_STRING					"Skaalaa…"
#define	FINNISH_SELECT_CANVAS_SIZE_STRING		"Valitse haluamasi piirtoalustan koko."
#define	FINNISH_SELECTED_COLORS_VIEW_MESSAGE1_STRING	"Klikkaa tässä avataksesi väri-ikkunan."
#define	FINNISH_SELECTOR_SHAPE_STRING			"Valitsimen Muoto"
#define	FINNISH_SELECTOR_TYPE_STRING			"VAlitsimen Tyyppi"
#define	FINNISH_SET_GRID_STRING					"Aseta Ruudukko"
#define	FINNISH_SET_ZOOM_LEVEL_STRING			"Aseta Suurennustaso"
#define	FINNISH_SETTINGS_HELP_STRING			"Tuo esille asetusikkunan."
#define	FINNISH_SETTINGS_STRING					"Asetukset…"
#define	FINNISH_SHAPE_STRING					"Muoto"
#define	FINNISH_SHEAR_STRING					"Shear"
#define	FINNISH_SHORTCUTS_HELP_STRING			"Avaa NetPositivella sivun, jossa kuvataan ArtPaintin näppäimistöoikotiet."
#define	FINNISH_SHORTCUTS_STRING				"Oikotiet…"
#define	FINNISH_SHOW_BRUSH_WINDOW_HELP_STRING	"Tuo esille sivellinikkunan."
#define	FINNISH_SHOW_BRUSH_WINDOW_STRING		"Näytä Sivellinikkuna"
#define	FINNISH_SHOW_LAYER_WINDOW_HELP_STRING	"Tuo esille kerrosikkunan."
#define	FINNISH_SHOW_LAYER_WINDOW_STRING		"Näytä Kerrosikkuna"
#define	FINNISH_SHOW_PALETTE_WINDOW_HELP_STRING	"Tuo esille paletti-ikkunan."
#define	FINNISH_SHOW_PALETTE_WINDOW_STRING		"Näytä Paletti-ikkuna"
#define	FINNISH_SHOW_TOOL_SETUP_WINDOW_HELP_STRING	"Tuo esille työkalunasetusikkunan."
#define	FINNISH_SHOW_TOOL_SETUP_WINDOW_STRING		"Näytä Työkalunasetusikkuna"
#define	FINNISH_SHOW_TOOL_WINDOW_HELP_STRING	"Tuo esille työkalunvalintaikkunan."
#define	FINNISH_SHOW_TOOL_WINDOW_STRING			"Näytä Työkalunvalintaikkuna"
#define	FINNISH_SHRINK_SELECTION_HELP_STRING	"Kutistaa valintaa hieman joka suunnasta."
#define	FINNISH_SHRINK_SELECTION_STRING			"Kutista Valintaa"
#define	FINNISH_SIZE_STRING						"Koko"
#define	FINNISH_STORE_BRUSH_STRING				"Talleta Sivellin"
#define	FINNISH_SPEED_STRING					"Nopeus"
#define	FINNISH_SPRAY_STRING					"Spray"
#define	FINNISH_SUBTRACT_AREA_STRING			"Vähennä Alue"
#define	FINNISH_TEXT_COLOR_STRING				"Tekstin Väri"
#define	FINNISH_TEXT_STRING						"Teksti"
#define	FINNISH_TOLERANCE_STRING				"Toleranssi"
#define	FINNISH_TOOLS_STRING					"Työkalut"
#define	FINNISH_TOOL_SETUP_STRING				"Työkalun Asetus"
#define	FINNISH_TOP_STRING						"Ylä"
#define	FINNISH_TRANSLATE_ALL_LAYERS_HELP_STRING	"Aloittaa kuvan liikuttamisen."
#define	FINNISH_TRANSLATE_LAYER_HELP_STRING		"Aloittaa aktiivisen kerroksen liikuttamisen."
#define	FINNISH_TRANSLATE_STRING				"Liikuta…"
#define	FINNISH_TRANSPARENT_STRING				"Läpinäkyvä"
#define	FINNISH_TRANSPARENCY_STRING				"Läpinäkyvyys"
#define	FINNISH_UNDO_HELP_STRING				"Peruu edellisen toiminnon."
#define	FINNISH_UNDO_NOT_AVAILABLE_STRING		"Ei Voi Perua"
#define	FINNISH_UNDO_SETTINGS_STRING			"Peruminen"
#define	FINNISH_UNDO_STRING						"Peru"
#define	FINNISH_UNLIMITED_STRING				"Rajoittamaton"
#define	FINNISH_UNTITLED_STRING					"Nimetön"
#define	FINNISH_USE_THE_TOOL_STRING				"Käytä työkalua painamalla hiiren nappia."
#define	FINNISH_USER_MANUAL_HELP_STRING			"Avaa NetPositivella ArtPaintin ohjeet."
#define	FINNISH_USER_MANUAL_STRING				"Käyttöohje…"
#define	FINNISH_USING_THE_TOOL_STRING			"Käyttää työkalua."
#define	FINNISH_VISIBLE_STRING					"Näkyvä"
#define	FINNISH_WAND_TOLERANCE_STRING			"Sauvan Toleranssi"
#define	FINNISH_WIDTH_STRING					"Leveys"
#define	FINNISH_WINDOW_FLOATING_STRING			"Ikkunat"
#define	FINNISH_WINDOW_STRING					"Ikkuna"
#define	FINNISH_ZOOM_IN_HELP_STRING				"Zoomaa kuvaan."
#define	FINNISH_ZOOM_IN_STRING					"Zoomaa Sisään"
#define	FINNISH_ZOOM_OUT_HELP_STRING			"Zoomaa ulos kuvasta."
#define	FINNISH_ZOOM_OUT_STRING					"Zoomaa Ulos"
#define	FINNISH_ZOOM_LEVEL_25_HELP_STRING		"Asettaa suurennustasoksi 25%."
#define	FINNISH_ZOOM_LEVEL_50_HELP_STRING		"Asettaa suurennustasoksi 50%."
#define	FINNISH_ZOOM_LEVEL_100_HELP_STRING		"Asettaa suurennustasoksi 100%."
#define	FINNISH_ZOOM_LEVEL_200_HELP_STRING		"Asettaa suurennustasoksi 200%."
#define	FINNISH_ZOOM_LEVEL_400_HELP_STRING		"Asettaa suurennustasoksi 400%."
#define	FINNISH_ZOOM_LEVEL_800_HELP_STRING		"Asettaa suurennustasoksi 800%."


// Here begin the tool name and help-string definitions.
#define	FINNISH_AIR_BRUSH_TOOL_NAME_STRING		"Maaliruisku"
#define	FINNISH_BLUR_TOOL_NAME_STRING			"Pehmennystyökalu"
#define	FINNISH_BRUSH_TOOL_NAME_STRING			"Sivellintyökalu"
#define	FINNISH_COLOR_SELECTOR_TOOL_NAME_STRING	"Värivalintatyökalu"
#define	FINNISH_ELLIPSE_TOOL_NAME_STRING		"Ellipsityökalu"
#define	FINNISH_ERASER_TOOL_NAME_STRING			"Pyyhekumi"
#define	FINNISH_FILL_TOOL_NAME_STRING			"Täyttötyökalu"
#define	FINNISH_FREE_LINE_TOOL_NAME_STRING		"Vapaa Viiva"
#define	FINNISH_HAIRY_BRUSH_TOOL_NAME_STRING	"Harjassivellin"
#define	FINNISH_RECTANGLE_TOOL_NAME_STRING		"Suorakaidetyökalu"
#define	FINNISH_SELECTOR_TOOL_NAME_STRING		"Valintatyökalu"
#define	FINNISH_STRAIGHT_LINE_TOOL_NAME_STRING	"Suora viiva"
#define	FINNISH_TEXT_TOOL_NAME_STRING			"Tekstityökalu"
#define	FINNISH_TRANSPARENCY_TOOL_NAME_STRING	"Läpinäkyvyystyökalu"

#define	FINNISH_AIR_BRUSH_TOOL_READY_STRING		"Paina hiiren nappia maalataksesi maaliruiskulla."
#define	FINNISH_BLUR_TOOL_READY_STRING			"Paina hiiren nappia pehmentääksesi kuvaa."
#define	FINNISH_BRUSH_TOOL_READY_STRING			"Paina hiiren nappia maalataksesi siveltimellä."
#define	FINNISH_COLOR_SELECTOR_TOOL_READY_STRING	"Paina hiiren nappia valitaksesi värin."
#define	FINNISH_ELLIPSE_TOOL_READY_STRING		"Paina hiiren nappia piirtääksesi ellipsin."
#define	FINNISH_ERASER_TOOL_READY_STRING			"Paina hiiren nappia käyttääksesi pyyhekumia."
#define	FINNISH_FILL_TOOL_READY_STRING			"Paina hiiren nappia tehdäksesi täytön."
#define	FINNISH_FREE_LINE_TOOL_READY_STRING		"Paina hiiren nappia piirtääksesi vapaan viivan."
#define	FINNISH_HAIRY_BRUSH_TOOL_READY_STRING	"Paina hiiren nappia maalataksesi harjassiveltimellä."
#define	FINNISH_RECTANGLE_TOOL_READY_STRING		"Paina hiiren nappia piirtääksesi suorakaiteen."
#define	FINNISH_SELECTOR_TOOL_READY_STRING		"Paina hiiren nappia tehdäksesi valinnan."
#define	FINNISH_STRAIGHT_LINE_TOOL_READY_STRING	"Paina hiiren nappia piirtääksesi suoran viivan."
#define	FINNISH_TEXT_TOOL_READY_STRING			"Paina hiiren nappia lisätäksesi kuvaan tekstiä."
#define	FINNISH_TRANSPARENCY_TOOL_READY_STRING	"Paina hiiren nappia säätääksesi kuvan läpinäkyvyyttä."

#define	FINNISH_AIR_BRUSH_TOOL_IN_USE_STRING		"Maalaa maaliruiskulla."
#define	FINNISH_BLUR_TOOL_IN_USE_STRING			"Sumentaa kuvaa."
#define	FINNISH_BRUSH_TOOL_IN_USE_STRING			"Maalaa siveltimellä."
#define	FINNISH_COLOR_SELECTOR_TOOL_IN_USE_STRING	"Valitsee väriä."
#define	FINNISH_ELLIPSE_TOOL_IN_USE_STRING		"Piirtää ellipsiä."
#define	FINNISH_ERASER_TOOL_IN_USE_STRING			"Pyyhkii kuvaa."
#define	FINNISH_FILL_TOOL_IN_USE_STRING			"Tekee täyttöä."
#define	FINNISH_FREE_LINE_TOOL_IN_USE_STRING		"Piirtää vapaata viivaa."
#define	FINNISH_HAIRY_BRUSH_TOOL_IN_USE_STRING	"Maalaa harjassiveltimellä."
#define	FINNISH_RECTANGLE_TOOL_IN_USE_STRING		"Piirtää suorakaidetta."
#define	FINNISH_SELECTOR_TOOL_IN_USE_STRING		"Tekee valintaa."
#define	FINNISH_STRAIGHT_LINE_TOOL_IN_USE_STRING	"Piirtää suoraa viivaa."
#define	FINNISH_TEXT_TOOL_IN_USE_STRING			"Lisää tekstiä kuvaan."
#define	FINNISH_TRANSPARENCY_TOOL_IN_USE_STRING	"Säätää kerroksen läpinäkyvyyttä."

#define FINNISH_MEMORY_ALERT_1_STRING			"Ei ole tarpeeksi vapaata muistia kerroksen lisäämiseen."\
												"Voit vapauttaa lisää muistia laittamalla perumisen pois päältä."\
												"Projekti kannattaa myös tallettaa tässä vaiheessa."\
												"Olen pahoillani aiheutuneesta epämukavuudesta."


#define	FINNISH_MEMORY_ALERT_2_STRING			"Ei ole tarpeeksi vapaata muistia pyytämäsi efektin aloittamiseen."\
												"Voit vapauttaa lisää muistia laittamalla perumisen pois päältä."\
												"Projekti kannattaa myös tallettaa tässä vaiheessa."\
												"Olen pahoillani aiheutuneesta epämukavuudesta."

#define	FINNISH_MEMORY_ALERT_3_STRING			"Ei ole tarpeeksi vapaata muistia pyytämäsi efektin viimeistelemiseen."\
												"Voit vapauttaa lisää muistia laittamalla perumisen pois päältä."\
												"Projekti kannattaa myös tallettaa tässä vaiheessa."\
												"Olen pahoillani aiheutuneesta epämukavuudesta."


#endif
